version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:5.0
    container_name: restoran-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Node.js application
  app:
    build: .
    container_name: restoran-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/restoran?authSource=admin
      - JWT_SECRET=restoran_jwt_secret_key_change_this_in_production
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data: